# Generated by Django 5.0 on 2023-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_post_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='institute',
            field=models.CharField(choices=[(1, 'KINS'), (2, 'NCS'), (3, 'UNIST'), (4, 'BRNC')], max_length=2),
        ),
    ]
