# Generated by Django 5.0 on 2023-12-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_post_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'N/Star'), ('2', '논문'), ('3', '보고서'), ('4', '일정')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='institute',
            field=models.CharField(choices=[('1', 'KINS'), ('2', 'NCS'), ('3', 'UNIST'), ('4', 'BRNC')], max_length=2),
        ),
    ]
