# Generated by Django 5.0 on 2023-12-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_alter_post_category_alter_post_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
