# Generated by Django 5.0 on 2023-12-19 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_remove_post_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='filename')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')),
                ('size', models.IntegerField(verbose_name='file size')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.post', verbose_name='Post')),
            ],
        ),
    ]
